# Model architecture
model = "vit_t"

# Training dataset
dataset = "tests/tiles"

# Simulation runtime in seconds
simulation_time = 1000

# Learning rate
learning_rate = 1e-5

# Dataloaders threads
num_workers = 1

# Batch size
batch_size = 16

# Test batch size
test_batch_size = 64

# Auxiliary loss learning rate
aux_learning_rate = 1e-3

# Use cuda
cuda = true

# Save model to disk
save = true

# Set random seed for reproducibility
seed = 42

# Path to a checkpoint
checkpoint = ""

# Time needed for communications in seconds
time_for_comms = 7.76    # Computed based on model size and downlink speed (10 Mbit/sec) * 2 

# estimated time per batch in seconds
time_per_batch = 2.014170143339369    # Benchmark performance using the GPU on the Unibap IX10-100 device profiling the function train_one_batch.

# Save all the models over time
save_checkpoints_over_time = true
