# Scenario 2: Low-altitude FL with relay 
# In this scenario we evaluate the latency when considering a system of 8 satellites in low-altitude sentinel-2 orbit, 
#  capturing data and training onboard, with 3 ground stations federating the model and 1 comm-satellite managing ISL to 
#  exchange data between satellites.

# Model architecture
model = "vit_t"

# Training dataset
dataset = "tests/tiles"

# Simulation runtime in seconds
simulation_time = 86400.0

# Learning rate
learning_rate = 1e-5

# Batch size
batch_size = 16

# Test batch size
test_batch_size = 64

# Auxiliary loss learning rate
aux_learning_rate = 1e-3

# Use cuda
cuda = true

# Save model to disk
save = true

# Set random seed for reproducibility
seed = 42

# Path to a checkpoint
checkpoint = ""

# Time needed for communications in seconds
time_for_comms = 3.88    # Computed based on model size and downlink speed (10 Mbit/sec). 

# estimated time per batch in seconds
time_per_batch = 8.532207639593826    # Benchmark performance using the CPU on the Unibap IX10-100 device profiling the function train_one_batch. (To be updated with GPU performance)

# Save all the models over time
save_checkpoints_over_time = true