name: decentralizedEO
channels:
  - conda-forge
  - pytorch
dependencies:
  - paseos
  - cudatoolkit   # Not available for ARM based cpu architecture.
  - dotmap
  - huggingface_hub # To download Worldfloods data from Hugging Face.
  - ipykernel
  - ipywidgets
  - loguru
  - mpi4py
  - numpy==1.23.5
  - pandas
  - pykep
  - python=3.10
  - pytorch
  - rasterio 
  - seaborn
  - scipy < 1.14.0
  - scikit-image
  - scikit-learn
  - scikit-spatial
  - skyfield
  - torchvision
  - toml
  - tqdm
  - gitpython
  - pip  # Include pip to handle pip installations for modules that are not available with conda.
  - pip:
      - segment_anything
      - timm